version: 1.0.{build}
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true 
before_build:
  - nuget restore
- provider: Environment
  name: production
  on:
    branch: master
    appveyor_repo_tag: true
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
